includes:
  - https://github.ibm.com/cloud-docs/fortigate-10g
  - https://github.ibm.com/cloud-docs/cloud-infrastructure
  - https://github.ibm.com/cloud-docs/icons
  - https://github.ibm.com/cloud-docs-solutions/infrastructure-hub